[CAR-48] Boilerplate additional setup
SoftwareBrothers/nest-mongo-boilerplate pull request #10
Opened 2020-01-21 12:30 UTC by paweljar

- updating of packages
- updating of swagger to newest version
- adding of kubernetes configuration
- adding support of ssl certs
- adding of sonarqube
- adding of admin-bro

2020-01-21 12:34 UTC, plorencrstit commented on docker-compose.yaml
> +      - ./docker/nginx:/etc/nginx
Are you sure about this? Won't you have too many files in `nginx` directory locally?

2020-01-21 12:35 UTC, plorencrstit commented on infrastructure/k8s/base/api-deployment.yml
> +            - name: FLOORPLANNER_API_KEY
You can remove anything regarding `floorplanner` which is very `skyhome` specific

2020-01-21 12:36 UTC, plorencrstit commented on infrastructure/k8s/environments/dev/api-secrets.yml
> +# To create values use: `echo -n 'secret-value' | base64` - and paste it under the data
This was my mistake in skyhome to have it in repository. It should be ingored. You should have only example of this file in repository.

2020-01-21 12:37 UTC, plorencrstit commented on package.json
> +    "@nestjs/swagger": "^4.1.12",
👍

2020-01-21 12:48 UTC, SimonB407 requested changes

2020-01-21 12:48 UTC, SimonB407 commented on infrastructure/k8s/base/api-deployment.yml
> +                secretKeyRef:
I would suggest something more readable, like in Leaderator we used:
```
envFrom:
            - configMapRef:
                name: env-config-map
            - secretRef:
                name: api-secrets
```

2020-01-21 12:48 UTC, SimonB407 commented on infrastructure/k8s/secrets/aws-secrets-example.yml
> +# To create values use: `echo -n 'secret-value' | base64` - and paste it under the data
If deployed to GCP this is unnecessary

2020-01-21 12:48 UTC, SimonB407 commented on src/backend/config/admin.ts
> +    companyName: 'Company name',
Can be changed to `Car Fellows` :smile:

2020-01-21 13:01 UTC, JonaszJestem approved these changes

2020-01-21 13:01 UTC, JonaszJestem commented on infrastructure/k8s/base/api-deployment.yml
> +          env:
```suggestion
          envFrom:
            - secretRef:
                name: api-secrets
```
no need to specify entry for each env variable if used like that
reference: [Leaderator - Deployment](https://github.com/SoftwareBrothers/leaderator-api/blob/master/k8s/base/api-deployment.yaml)

2020-01-21 13:01 UTC, JonaszJestem commented on infrastructure/k8s/environments/dev/api-ingress.yml
> +  - host: api-dev.skyhome.no
skyhome leftover

2020-01-21 13:01 UTC, JonaszJestem commented on infrastructure/k8s/environments/staging/api-ingress.yml
> +  - host: api-staging.skyhome.no
skyhome leftover

2020-01-21 13:01 UTC, JonaszJestem commented on infrastructure/k8s/environments/staging/api-secrets.yml
> +# To create values use: `echo -n 'secret-value' | base64` - and paste it under the data
I don't know how much time you have for this task, but there is a solution in leaderator for automatically fill kubernetes secret values using envs. That way you don't have to store them as Base64 in repository
Reference: 
[Script](https://github.com/SoftwareBrothers/leaderator-api/blob/master/k8s/util/replace-envs.sh) which replaces e.g {{ DB_PASS }} with $DB_PASS env.
[Step in CD](https://github.com/SoftwareBrothers/leaderator-api/blob/master/codeship-steps.yml) Line 59

2020-01-21 13:01 UTC, JonaszJestem commented on infrastructure/set-sentry-release.sh
> +export SENTRY_ORG=organization_name
organization is always `softbro` except when you want to run it on client sentry account. Is it for that purpose?

2020-01-21 13:01 UTC, JonaszJestem commented on src/backend/admin/admin.plugin.ts
> +const AdminBro = require('admin-bro');
AFAIK all typings are fixed in admin bro so it can be imported normally
```suggestion
import AdminBro from 'admin-bro';
```

2020-01-21 16:22 UTC, paweljar commented on docker-compose.yaml
> +      - ./docker/nginx:/etc/nginx
Of course not, I forgot to remove this part. Thanks!

2020-01-21 16:23 UTC, paweljar commented on infrastructure/k8s/base/api-deployment.yml
> +            - name: FLOORPLANNER_API_KEY
Done

2020-01-21 16:35 UTC, paweljar commented on infrastructure/k8s/environments/dev/api-secrets.yml
> +# To create values use: `echo -n 'secret-value' | base64` - and paste it under the data
Done

2020-01-21 16:39 UTC, paweljar commented on infrastructure/k8s/secrets/aws-secrets-example.yml
> +# To create values use: `echo -n 'secret-value' | base64` - and paste it under the data
It should be common boilerplate so maybe it's worth to leave it as it is?

In my opinion, a good idea would have separate configurations for GCP (functions and Kubernetes) and AWS (lambda and Kubernetes).

2020-01-21 16:40 UTC, paweljar commented on src/backend/config/admin.ts
> +    companyName: 'Company name',
No, because it is the common boilerplate :)

2020-01-21 16:41 UTC, paweljar commented on infrastructure/k8s/environments/dev/api-ingress.yml
> +  - host: api-dev.skyhome.no
Fixed

2020-01-21 16:41 UTC, paweljar commented on infrastructure/k8s/environments/staging/api-ingress.yml
> +  - host: api-staging.skyhome.no
Fixed

2020-01-21 16:42 UTC, paweljar commented on infrastructure/k8s/environments/staging/api-secrets.yml
> +# To create values use: `echo -n 'secret-value' | base64` - and paste it under the data
Thanks, I'll do it in this task.

2020-01-21 16:42 UTC, paweljar commented on infrastructure/k8s/base/api-deployment.yml
> +                secretKeyRef:
Thanks, I'll do it in this task.

2020-01-21 16:42 UTC, paweljar commented on infrastructure/k8s/base/api-deployment.yml
> +          env:
Thanks, I'll do it in this task.

2020-01-21 16:45 UTC, paweljar commented on infrastructure/set-sentry-release.sh
> +export SENTRY_ORG=organization_name
I didn't think about it. For me this is ok.

2020-01-22 09:39 UTC, SimonB407 commented on infrastructure/k8s/environments/dev/api-ingress.yml
> +  - host: api-dev.skyhome.no
Emm, it's not?

2020-01-22 09:41 UTC, SimonB407 approved these changes

2020-01-22 09:43 UTC, JonaszJestem commented on .gitignore
> +infrastructure/k8s/environments/**/api-secrets.yml
Without this file in repository Kubernetes will not have any secrets defined during deployment

2020-01-22 13:42 UTC, plorencrstit commented on .gitignore
> +# infrasructure
spell typo: `infrastructure` instead of `infrasructure`

2020-01-22 13:46 UTC, plorencrstit approved these changes

2020-01-22 13:47 UTC, paweljar commented on .gitignore
> +# infrasructure
Fixed

2020-01-22 13:56 UTC, JonaszJestem approved these changes

2020-01-22 13:56 UTC, JonaszJestem commented on src/backend/admin/resources/index.ts
> +export default (connection: mongoose.Connection): Array<any> => {
Optional, there is probably some type in AdminBro for that

2020-01-22 13:56 UTC, JonaszJestem commented on src/backend/config/admin.ts
> +export default (connection): Object => ({
Optional, same here, there is probably some interface like `AdminBroOptions`

2020-01-22 13:56 UTC, JonaszJestem commented on .eslintrc.json
> +    "jest/expect-expect": "off",
That probably shouldn't be disabled, proper configuration for the rule to align with `supertest` library is on the bottom of this page: [Eslint expect-expect](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/expect-expect.md)

2020-01-22 14:05 UTC, RiledUpCrow reviewed
Can someone explain `start`, `start:dev` and `start:debug` scripts in package.json? It seems neither of them starts the application in a live reload development mode. `start` runs the code through `ts-node` once and doesn't watch for changes, `start:dev` builds and watches compiled output (why?), and `start:debug` has `--inspect-brk` flag passed to node which means it will hang until someone connects with a debugger and unlocks it.

I know this isn't the part of this PR, but can we have just one start script that simply runs the code in debug mode (without breakpoint at the beginning) via node and ts-node?

2020-01-22 14:07 UTC, Co0sh commented on .eslintrc.json
> +    "jest/expect-expect": "off",
This is because some tests don't use jest's `expect` functions.

2020-01-22 14:14 UTC, paweljar commented on infrastructure/k8s/environments/dev/api-ingress.yml
> +  - host: api-dev.skyhome.no
Is it? :)

2020-01-22 14:17 UTC, RiledUpCrow requested changes

2020-01-22 14:17 UTC, Co0sh commented on docker-compose.yaml
> +    container_name: sonarqube
Can you add `${APP_NAME}` to the name? This way the container will not conflict with other projects when running at the same time. Alternatively remove container names altogether and let docker-compose give those names based on the directory it's running from.

2020-01-22 14:17 UTC, Co0sh commented on .gitignore
> +infrastructure/k8s/environments/**/api-secrets.yml
There's `api-secrets.yml.dist`, we should probably add an instruction to copy it to the documentation/readme.

2020-01-22 14:17 UTC, Co0sh commented on src/backend/admin/authentication/admin-auth.config.ts
> +      password: await Argon2.hash(process.env.ADMIN_PASSWORD),
We should document adding these environment variables to the app.

2020-01-23 19:16 UTC, JonaszJestem commented on .eslintrc.json
> +    "jest/expect-expect": "off",
Yeah, I looked up the test files and there are `supertest` expectations - in the link I have included there is a example of workaround to resolve this issue.

2021-08-06 20:32 UTC, closed without merging